name: Deploy API-PRD

on:
  push:
    branches:
      - master
    paths:
      - apps/api/**

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run yarn install
        run: yarn install

      - name: Build packages/dtos
        run: cd packages/dtos && yarn build

      - name: Build apps/api
        run: cd apps/api && yarn build

      - name: Serverless
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./apps/api && serverless deploy --stage prd"
          entrypoint: /bin/sh
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
